name: "calculate_claim_value"
backend: "python"

input [
  {
    name: "total_claim_amount"
    data_type: TYPE_INT64
    dims: [ 1 ]
  }
]
output [
  {
    name: "claim_value"
    data_type: TYPE_FP64
    dims: [ 1 ]
  }
]

instance_group [{ kind: KIND_CPU }]
