apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: classify_claim_complexity
  namespace: seldon-mesh
spec:
  storageUri: "/mnt/models/insurance_claims/classify_claim_complexity"
  requirements:
  - triton
  - python
